make -C $(SUBDIR)	-C always auto bind with -w (--print-directory)

cfile :=  $(wildcard $(main_src)/*.c)
cfile +=  $(wildcard $(test_src)/*.c)
objects := $(cfile:.c=.o )

obj-m := mmiotool.o (module name)
mmiotool-objs := mmiotool_test.o xxx.o yyy.o (module components)
make -C build/linux-board-compiled
make ARCH=arm CROSS_COMPILE=armv6jel-target-linux-gnueabi- (essetial '-')
#include <march/comcerto-1000.h>    arch/arm/mach-comcerto/include/mach/comcerto-1000.h

FBINCDIR = $(shell if [ -d /opt/firebird/include ]; then echo /opt/firebird/include; else echo nul; fi)
